[project]
name = "caterpillar-f25-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.3.5",
    "requests>=2.32.3",
    "types-requests>=2.32.0.20250328",
]
